os: linux

language: python

python:
    - 3.6
    - 3.7

addons:
    postgresql: "11"
    apt:
        packages:
            - postgresql-11
            - postgresql-client-11
before_install:
    - pip install poetry

install:
    - poetry install -v
    - pip install codecov

before_script:
    - sudo systemctl start postgresql
    - psql -c 'create database roax_postgresql;' -U postgres

script:
    - pytest --cov=roax --cov-report=xml tests/

after_success:
    - codecov
