name: test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]

    steps:

    - uses: actions/checkout@v2

    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: 'latest'
        postgresql db: 'fondat-postgres'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry package
      run: pip install poetry

    - name: Install project dependencies
      run: poetry install -v

    - name: Test project
      run: poetry run pytest --cov=fondat-postgres tests/
